### ISSUE TITLE
Project Deployment

### ISSUE THREAD

**Issue by Mhamad-Raad** [Mhamad-Raad/Microverse-Portfolio#11]
in this branch we have done the following:

- deploy the project.
- add the demo link to the readme file.

**Comment by ichala** [comment]
Hi @Mhamad-Raad,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Website Deployed and working fine ✔️
- Added link to Readme file✔️


 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
*************************************
# Optional Suggestions 

- [x]  N/A



_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._v
